services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # ğŸ‘‡ ë¹Œë“œ í”Œë«í¼ì„ ì§€ì •í•©ë‹ˆë‹¤.
    platform: linux/amd64
    container_name: rps-game
    ports:
      - '3005:3005'
    restart: unless-stopped
